const products = [
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/2.png",
    title: "Кольцо BVLGARI B.ZERO DIAMONDS",
    price: 7888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Серьги",
  },
  {
    img: "products/3.png",
    title: "Кулон No name С ТАНЗАНИТОМ 7.59 КАРАТА И БРИЛЛИАНТАМИ",
    price: 1888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Кулон",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 1888000,
    state: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Серьги",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Подвеска",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 9888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 4888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Кольцо",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 5888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 6888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Кольцо",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Колье",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 7888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Кольцо",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 1888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Серьги",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Кольцо",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 1888000,
    state: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Кулон",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Кулон",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 9888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Кулон",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Б/У",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Подвеска",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 4888000,
    state: "Новые",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Подвеска",
  },
  {
    img: "products/1.png",
    title: "Серьги Chopard LA STRADA",
    price: 3888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Подвеска",
  },
  {
    img: "products/2.png",
    title: "Серьги Chopard LA STRADA",
    price: 5888000,
    state: "Новые",
    collection: "Мужские",
    brand: "A. LANGE &  SOHNE",
    type: "Подвеска",
  },
  {
    img: "products/3.png",
    title: "Серьги Chopard LA STRADA",
    price: 6888000,
    state: "Б/У",
    collection: "Женские",
    brand: "A. LANGE &  SOHNE",
    type: "Серьги",
  },
];

export { products };
